import { ExternalLink, Github, ArrowRight } from "lucide-react";
import ScrollReveal from "../ScrollReveal";
import { motion } from "framer-motion";
import { projects, Project } from "@/data/projects";
import { Link } from "react-router-dom";

const ProjectCard=({project,index}:{project:Project;index:number})=><ScrollReveal delay={index*0.12}><motion.article whileHover={{y:-4}} className="group relative p-6 md:p-8 rounded-2xl bg-card/50 border border-border/50 hover:border-border hover:bg-surface transition-all duration-500"><div className="relative z-10"><div className="flex items-start justify-between gap-5 mb-4"><h3 className="text-xl md:text-2xl font-medium text-foreground group-hover:text-primary">{project.title}</h3><div className="flex items-center gap-3 shrink-0">{project.githubUrl&&<a href={project.githubUrl} target="_blank" rel="noreferrer" aria-label="View source on GitHub" className="text-muted-foreground hover:text-foreground"><Github className="w-5 h-5"/></a>}{project.liveUrl&&<a href={project.liveUrl} target="_blank" rel="noreferrer" aria-label="View live project" className="text-muted-foreground hover:text-foreground"><ExternalLink className="w-5 h-5"/></a>}</div></div><p className="text-muted-foreground leading-relaxed mb-6">{project.description}</p><div className="flex flex-wrap gap-2">{project.tags.map(tag=><span key={tag} className="text-xs font-mono text-muted-foreground/80 px-3 py-1 rounded-full bg-secondary/50 border border-border/30">{tag}</span>)}</div></div></motion.article></ScrollReveal>;

const Projects=()=> <section id="projects" className="py-28 relative"><div className="container px-6 md:px-8"><div className="max-w-4xl mx-auto"><ScrollReveal><span className="inline-block text-sm font-mono text-primary/80 tracking-wider uppercase mb-4">Projects</span></ScrollReveal><ScrollReveal delay={0.1}><h2 className="text-3xl md:text-4xl font-medium tracking-tight mb-4">Work I can show</h2></ScrollReveal><ScrollReveal delay={0.15}><p className="text-muted-foreground text-lg mb-12 max-w-2xl">A small set of public projects that demonstrate what I actually build.</p></ScrollReveal><div className="grid gap-6">{projects.map((project,index)=><ProjectCard key={project.title} project={project} index={index}/>)}<ScrollReveal delay={0.3}><Link to="/projects" className="group inline-flex items-center gap-2 text-sm font-medium text-primary hover:text-foreground">View project archive <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform"/></Link></ScrollReveal></div></div></div></section>;
export default Projects;